export const data = {
    verbList: [
        {Infinitif : "anbieten" , Present : "bietet an" , Preterit : "bot an" , Parfait : "hat angeboten" , Traduction : "offrir, proposer" ,},
        {Infinitif : "anfangen" , Present : "fängt an" , Preterit : "fing an" , Parfait : "hat angefangen" , Traduction : "commencer" ,},
        {Infinitif : "anziehen" , Present : "zieht an" , Preterit : "zog an" , Parfait : "hat angezogen" , Traduction : "mettre (vêtement)" ,},
        {Infinitif : "aufgeben" , Present : "gibt auf" , Preterit : "gab auf" , Parfait : "hat aufgegeben" , Traduction : "abandonner" ,},
        {Infinitif : "ausblasen" , Present : "bläst aus" , Preterit : "blies aus" , Parfait : "hat ausgeblasen" , Traduction : "souffler (bougie)" ,},
        {Infinitif : "ausgeben" , Present : "gibt aus" , Preterit : "gab aus" , Parfait : "hat ausgegeben" , Traduction : "dépenser (argent)" ,},
        {Infinitif : "aussehen" , Present : "sieht aus" , Preterit : "sah aus" , Parfait : "hat ausgesehen" , Traduction : "avoir l'air" ,},
        {Infinitif : "ausziehen" , Present : "zieht aus" , Preterit : "zog aus" , Parfait : "hat ausgezogen" , Traduction : "enlever (vêtement)" ,},
        {Infinitif : "ausziehen" , Present : "zieht aus" , Preterit : "zog aus" , Parfait : "ist ausgezogen" , Traduction : "déménager" ,},
        {Infinitif : "backen" , Present : "bäckt" , Preterit : "backte / buk" , Parfait : "hat gebacken" , Traduction : "faire cuire au four (pâtisserie)" ,},
        {Infinitif : "befehlen" , Present : "befiehlt" , Preterit : "befahl" , Parfait : "hat befohlen" , Traduction : "donner un ordre" ,},
        {Infinitif : "sich befinden" , Present : "befindet sich" , Preterit : "befand sich" , Parfait : "hat sich befunden" , Traduction : "se trouver" ,},
        {Infinitif : "beginnen" , Present : "beginnt" , Preterit : "begann" , Parfait : "hat begonnen" , Traduction : "commencer" ,},
        {Infinitif : "beißen" , Present : "beißt" , Preterit : "biss" , Parfait : "hat gebissen" , Traduction : "mordre" ,},
        {Infinitif : "beschreiben" , Present : "beschreibt" , Preterit : "beschrieb" , Parfait : "hat beschrieben" , Traduction : "décrire" ,},
        {Infinitif : "binden" , Present : "bindet" , Preterit : "band" , Parfait : "hat gebunden" , Traduction : "attacher" ,},
        {Infinitif : "bitten" , Present : "bittet" , Preterit : "bat" , Parfait : "hat gebeten" , Traduction : "prier, demander (poliment)" ,},
        {Infinitif : "bleiben" , Present : "bleibt" , Preterit : "blieb" , Parfait : "ist geblieben" , Traduction : "rester" ,},
        {Infinitif : "brennen" , Present : "brennt" , Preterit : "brannte" , Parfait : "hat gebrannt" , Traduction : "brûler" ,},
        {Infinitif : "bringen" , Present : "bringt" , Preterit : "brachte" , Parfait : "hat gebracht" , Traduction : "apporter" ,},
        {Infinitif : "denken" , Present : "denkt" , Preterit : "dachte" , Parfait : "hat gedacht" , Traduction : "penser" ,},
        {Infinitif : "dürfen" , Present : "darf" , Preterit : "durfte" , Parfait : "hat gedurft" , Traduction : "avoir le droit" ,},
        {Infinitif : "einladen" , Present : "lädt ein" , Preterit : "lud ein" , Parfait : "hat eingeladen" , Traduction : "inviter" ,},
        {Infinitif : "empfangen" , Present : "empfängt" , Preterit : "empfing" , Parfait : "hat empfangen" , Traduction : "recevoir" ,},
        {Infinitif : "empfinden" , Present : "empfindet" , Preterit : "empfand" , Parfait : "hat empfunden" , Traduction : "ressentir" ,},
        {Infinitif : "sich entschließen" , Present : "entschließt sich" , Preterit : "entschloss sich" , Parfait : "hat sich entschlossen" , Traduction : "se décider" ,},
        {Infinitif : "erfahren" , Present : "erfährt" , Preterit : "erfuhr" , Parfait : "hat erfahren" , Traduction : "apprendre (une nouvelle)" ,},
        {Infinitif : "ertragen" , Present : "erträgt" , Preterit : "ertrug" , Parfait : "hat ertragen" , Traduction : "supporter (un problème)" ,},
        {Infinitif : "erziehen" , Present : "erzieht" , Preterit : "erzog" , Parfait : "hat erzogen" , Traduction : "éduquer" ,},
        {Infinitif : "essen" , Present : "isst" , Preterit : "aß" , Parfait : "hat gegessen" , Traduction : "manger" ,},
        {Infinitif : "fahren" , Present : "fährt" , Preterit : "fuhr" , Parfait : "ist gefahren" , Traduction : "aller (en véhicule)" ,},
        {Infinitif : "fallen" , Present : "fällt" , Preterit : "fiel" , Parfait : "ist gefallen" , Traduction : "tomber" ,},
        {Infinitif : "fangen" , Present : "fängt" , Preterit : "fing" , Parfait : "hat gefangen" , Traduction : "attraper" ,},
        {Infinitif : "fernsehen" , Present : "sieht fern" , Preterit : "sah fern" , Parfait : "hat ferngesehen" , Traduction : "regarder la télévision" ,},
        {Infinitif : "finden" , Present : "findet" , Preterit : "fand" , Parfait : "hat gefunden" , Traduction : "trouver" ,},
        {Infinitif : "fliegen" , Present : "fliegt" , Preterit : "flog" , Parfait : "ist geflogen" , Traduction : "voler (avion, oiseau)" ,},
        {Infinitif : "fliehen" , Present : "flieht" , Preterit : "floh" , Parfait : "ist geflohen" , Traduction : "fuir" ,},
        {Infinitif : "fließen" , Present : "fließt" , Preterit : "floß" , Parfait : "ist geflossen" , Traduction : "couler" ,},
        {Infinitif : "fressen" , Present : "frisst" , Preterit : "fraß" , Parfait : "hat gefressen" , Traduction : "bouffer, manger (animaux)" ,},
        {Infinitif : "frieren" , Present : "friert" , Preterit : "fror" , Parfait : "hat gefroren" , Traduction : "geler, avoir froid" ,},
        {Infinitif : "geben" , Present : "gibt" , Preterit : "gab" , Parfait : "hat gegeben" , Traduction : "donner" ,},
        {Infinitif : "gefallen" , Present : "gefällt" , Preterit : "gefiel" , Parfait : "hat gefallen" , Traduction : "plaire" ,},
        {Infinitif : "gehen" , Present : "geht" , Preterit : "ging" , Parfait : "ist gegangen" , Traduction : "aller (à pied)" ,},
        {Infinitif : "gelingen" , Present : "gelingt" , Preterit : "gelang" , Parfait : "ist gelungen" , Traduction : "réussir" ,},
        {Infinitif : "geschehen" , Present : "geschieht" , Preterit : "geschah" , Parfait : "ist geschehen" , Traduction : "arriver, se passer" ,},
        {Infinitif : "gewinnen" , Present : "gewinnt" , Preterit : "gewann" , Parfait : "hat gewonnen" , Traduction : "gagner" ,},
        {Infinitif : "gießen" , Present : "gießt" , Preterit : "goss" , Parfait : "hat gegossen" , Traduction : "verser" ,},
        {Infinitif : "gleichen" , Present : "gleicht" , Preterit : "glich" , Parfait : "hat geglichen" , Traduction : "ressembler" ,},
        {Infinitif : "haben" , Present : "hat" , Preterit : "hatte" , Parfait : "hat gehabt" , Traduction : "avoir" ,},
        {Infinitif : "halten" , Present : "hält" , Preterit : "hielt" , Parfait : "hat gehalten" , Traduction : "tenir; arrêter" ,},
        {Infinitif : "hängen" , Present : "hängt" , Preterit : "hing" , Parfait : "hat gehangen" , Traduction : "être suspendu, être accroché" ,},
        {Infinitif : "heißen" , Present : "heißt" , Preterit : "hieß" , Parfait : "hat geheißen" , Traduction : "s'appeler" ,},
        {Infinitif : "helfen" , Present : "hilft" , Preterit : "half" , Parfait : "hat geholfen" , Traduction : "aider" ,},
        {Infinitif : "kennen" , Present : "kennt" , Preterit : "kannte" , Parfait : "hat gekannt" , Traduction : "connaître" ,},
        {Infinitif : "kommen" , Present : "kommt" , Preterit : "kam" , Parfait : "ist gekommen" , Traduction : "venir" ,},
        {Infinitif : "können" , Present : "kann" , Preterit : "konnte" , Parfait : "hat gekonnt" , Traduction : "pouvoir, savoir" ,},
        {Infinitif : "lassen" , Present : "lässt" , Preterit : "ließ" , Parfait : "hat gelassen" , Traduction : "laisser" ,},
        {Infinitif : "laufen" , Present : "läuft" , Preterit : "lief" , Parfait : "ist gelaufen" , Traduction : "aller, courir" ,},
        {Infinitif : "leiden" , Present : "leidet" , Preterit : "litt" , Parfait : "hat gelitten" , Traduction : "souffrir" ,},
        {Infinitif : "leihen" , Present : "leiht" , Preterit : "lieh" , Parfait : "hat geliehen" , Traduction : "prêter" ,},
        {Infinitif : "lesen" , Present : "liest" , Preterit : "las" , Parfait : "hat gelesen" , Traduction : "lire" ,},
        {Infinitif : "liegen" , Present : "liegt" , Preterit : "lag" , Parfait : "hat gelegen" , Traduction : "être allongé, posé, situé" ,},
        {Infinitif : "lügen" , Present : "lügt" , Preterit : "log" , Parfait : "hat gelogen" , Traduction : "mentir" ,},
        {Infinitif : "mitnehmen" , Present : "nimmt mit" , Preterit : "nahm mit" , Parfait : "hat mitgenommen" , Traduction : "emmener" ,},
        {Infinitif : "mögen" , Present : "mag" , Preterit : "mochte" , Parfait : "hat gemocht" , Traduction : "aimer bien" ,},
        {Infinitif : "müssen" , Present : "muss" , Preterit : "musste" , Parfait : "hat gemusst" , Traduction : "être obligé" ,},
        {Infinitif : "nehmen" , Present : "nimmt" , Preterit : "nahm" , Parfait : "hat genommen" , Traduction : "prendre" ,},
        {Infinitif : "nennen" , Present : "nennt" , Preterit : "nannte" , Parfait : "hat genannt" , Traduction : "appeler (par un nom)" ,},
        {Infinitif : "raten" , Present : "rät" , Preterit : "riet" , Parfait : "hat geraten" , Traduction : "conseiller, conseiller" ,},
        {Infinitif : "reiten" , Present : "reitet" , Preterit : "ritt" , Parfait : "hat geritten" , Traduction : "faire du cheval" ,},
        {Infinitif : "rennen" , Present : "rennt" , Preterit : "rannte" , Parfait : "ist gerannt" , Traduction : "courir (vite)" ,},
        {Infinitif : "riechen" , Present : "riecht" , Preterit : "roch" , Parfait : "hat gerochen" , Traduction : "sentir (odeur)" ,},
        {Infinitif : "rufen" , Present : "ruft" , Preterit : "rief" , Parfait : "hat gerufen" , Traduction : "appeler, crier" ,},
        {Infinitif : "scheinen" , Present : "scheint" , Preterit : "schien" , Parfait : "hat geschienen" , Traduction : "briller; sembler" ,},
        {Infinitif : "schießen" , Present : "schießt" , Preterit : "schoss" , Parfait : "hat geschossen" , Traduction : "tirer (un projectile)" ,},
        {Infinitif : "schlafen" , Present : "schläft" , Preterit : "schlief" , Parfait : "hat geschlafen" , Traduction : "dormir" ,},
        {Infinitif : "schlagen" , Present : "schlägt" , Preterit : "schlug" , Parfait : "hat geschlagen" , Traduction : "frapper, battre, taper" ,},
        {Infinitif : "schließen" , Present : "schließt" , Preterit : "schloss" , Parfait : "hat geschlossen" , Traduction : "fermer" ,},
        {Infinitif : "schneiden" , Present : "schneidet" , Preterit : "schnitt" , Parfait : "hat geschnitten" , Traduction : "couper" ,},
        {Infinitif : "schreiben" , Present : "schreibt" , Preterit : "schrieb" , Parfait : "hat geschrieben" , Traduction : "écrire" ,},
        {Infinitif : "schreien" , Present : "schreit" , Preterit : "schrie" , Parfait : "hat geschrieen" , Traduction : "crier (fort)" ,},
        {Infinitif : "schweigen" , Present : "schweigt" , Preterit : "schwieg" , Parfait : "hat geschwiegen" , Traduction : "se taire" ,},
        {Infinitif : "schwimmen" , Present : "schwimmt" , Preterit : "schwamm" , Parfait : "ist geschwommen" , Traduction : "nager" ,},
        {Infinitif : "sehen" , Present : "sieht" , Preterit : "sah" , Parfait : "hat gesehen" , Traduction : "voir" ,},
        {Infinitif : "sein" , Present : "ist" , Preterit : "war" , Parfait : "ist gewesen" , Traduction : "être" ,},
        {Infinitif : "singen" , Present : "singt" , Preterit : "sang" , Parfait : "hat gesungen" , Traduction : "chanter" ,},
        {Infinitif : "sitzen" , Present : "sitzt" , Preterit : "saß" , Parfait : "hat gesessen" , Traduction : "être assis" ,},
        {Infinitif : "sollen" , Present : "soll" , Preterit : "sollte" , Parfait : "hat gesollt" , Traduction : "devoir, avoir l'obligation morale" ,},
        {Infinitif : "sprechen" , Present : "spricht" , Preterit : "sprach" , Parfait : "hat gesprochen" , Traduction : "parler" ,},
        {Infinitif : "springen" , Present : "springt" , Preterit : "sprang" , Parfait : "ist gesprungen" , Traduction : "sauter" ,},
        {Infinitif : "stehen" , Present : "steht" , Preterit : "stand" , Parfait : "hat gestanden" , Traduction : "être debout" ,},
        {Infinitif : "stehlen" , Present : "stiehlt" , Preterit : "stahl" , Parfait : "hat gestohlen" , Traduction : "voler, dérober" ,},
        {Infinitif : "steigen" , Present : "steigt" , Preterit : "stieg" , Parfait : "ist gestiegen" , Traduction : "monter" ,},
        {Infinitif : "sterben" , Present : "stirbt" , Preterit : "starb" , Parfait : "ist gestorben" , Traduction : "mourir" ,},
        {Infinitif : "(sich) streiten" , Present : "streitet (sich)" , Preterit : "stritt (sich)" , Parfait : "hat (sich) gestritten" , Traduction : "se disputer" ,},
        {Infinitif : "tragen" , Present : "trägt" , Preterit : "trug" , Parfait : "hat getragen" , Traduction : "porter" ,},
        {Infinitif : "(sich) treffen" , Present : "trifft (sich)" , Preterit : "traf (sich)" , Parfait : "hat (sich) getroffen" , Traduction : "(se) rencontrer" ,},
        {Infinitif : "treiben" , Present : "treibt" , Preterit : "trieb" , Parfait : "hat getrieben" , Traduction : "faire (du sport)" ,},
        {Infinitif : "treten" , Present : "tritt" , Preterit : "trat" , Parfait : "ist getreten" , Traduction : "donner un coup de" ,},
        {Infinitif : "trinken" , Present : "trinkt" , Preterit : "trank" , Parfait : "hat getrunken" , Traduction : "boire" ,},
        {Infinitif : "tun" , Present : "tut" , Preterit : "tat" , Parfait : "hat getan" , Traduction : "faire (familier)" ,},
        {Infinitif : "umziehen" , Present : "zieht um" , Preterit : "zog um" , Parfait : "ist umgezogen" , Traduction : "déménager" ,},
        {Infinitif : "unterbrechen" , Present : "unterbricht" , Preterit : "unterbrach" , Parfait : "hat unterbrochen" , Traduction : "interrompre" ,},
        {Infinitif : "unternehmen" , Present : "unternimmt" , Preterit : "unternahm" , Parfait : "hat unternommen" , Traduction : "entreprendre" ,},
        {Infinitif : "verbieten" , Present : "verbietet" , Preterit : "verbot" , Parfait : "hat verboten" , Traduction : "interdire" ,},
        {Infinitif : "verbringen" , Present : "verbringt" , Preterit : "verbrachte" , Parfait : "hat verbracht" , Traduction : "passer (du temps)" ,},
        {Infinitif : "vergessen" , Present : "vergisst" , Preterit : "vergaß" , Parfait : "hat vergessen" , Traduction : "oublier" ,},
        {Infinitif : "verlassen" , Present : "verlässt" , Preterit : "verließ" , Parfait : "hat verlassen" , Traduction : "quitter" ,},
        {Infinitif : "verlieren" , Present : "verliert" , Preterit : "verlor" , Parfait : "hat verloren" , Traduction : "perdre" ,},
        {Infinitif : "vermeiden" , Present : "vermeidet" , Preterit : "vermied" , Parfait : "hat vermieden" , Traduction : "éviter" ,},
        {Infinitif : "verschwinden" , Present : "verschwindet" , Preterit : "verschwand" , Parfait : "ist verschwunden" , Traduction : "disparaître" ,},
        {Infinitif : "verzeihen" , Present : "verzeiht" , Preterit : "verzieh" , Parfait : "hat verziehen" , Traduction : "pardonner" ,},
        {Infinitif : "vorschlagen" , Present : "schlägt vor" , Preterit : "schlug vor" , Parfait : "hat vorgeschlagen" , Traduction : "proposer" ,},
        {Infinitif : "wachsen" , Present : "wächst" , Preterit : "wuchs" , Parfait : "ist gewachsen" , Traduction : "pousser, grandir" ,},
        {Infinitif : "waschen" , Present : "wäscht" , Preterit : "wusch" , Parfait : "hat gewaschen" , Traduction : "laver" ,},
        {Infinitif : "werben" , Present : "wirbt" , Preterit : "warb" , Parfait : "hat geworben" , Traduction : "faire de la publicité" ,},
        {Infinitif : "werden" , Present : "wird" , Preterit : "wurde" , Parfait : "ist geworden" , Traduction : "devenir" ,},
        {Infinitif : "werfen" , Present : "wirft" , Preterit : "warf" , Parfait : "hat geworfen" , Traduction : "lancer, jeter" ,},
        {Infinitif : "wissen" , Present : "weiß" , Preterit : "wusste" , Parfait : "hat gewusst" , Traduction : "savoir" ,},
        {Infinitif : "wollen" , Present : "will" , Preterit : "wollte" , Parfait : "hat gewollt" , Traduction : "vouloir" ,},
        {Infinitif : "zerbrechen" , Present : "zerbricht" , Preterit : "zerbrach" , Parfait : "hat zerbrochen" , Traduction : "casser (en morceaux)" ,},
        {Infinitif : "ziehen" , Present : "zieht" , Preterit : "zog" , Parfait : "ist gezogen" , Traduction : "tirer (vers soi)" ,},
        {Infinitif : "zwingen" , Present : "zwingt" , Preterit : "zwang" , Parfait : "hat gezwungen" , Traduction : "contraindre, obliger" ,},
    ],
    verbTest: [
        {title: "Page 1", number: 1, testLength:32, testStart: 0, testEnd: 31},
        {title: "Page 2", number: 2, testLength:32, testStart: 32, testEnd: 63},
        {title: "Page 3", number: 3, testLength:32, testStart: 64, testEnd: 95},
        {title: "Page 4", number: 4, testLength:27, testStart: 96, testEnd: 122},
        {title: "Page 1 - Partie 1/2", number: 5, testLength:16, testStart: 0, testEnd: 15},
        {title: "Page 1 - Partie 2/2", number: 6, testLength:16, testStart: 16, testEnd: 31},
        {title: "Page 2 - Partie 1/2", number: 7, testLength:16, testStart: 32, testEnd: 47},
        {title: "Page 2 - Partie 2/2", number: 8, testLength:16, testStart: 48, testEnd: 63},
        {title: "Page 3 - Partie 1/2", number: 9, testLength:16, testStart: 64, testEnd: 79},
        {title: "Page 3 - Partie 2/2", number: 10, testLength:16, testStart: 80, testEnd: 95},
        {title: "Page 4 - Partie 1/2", number: 11, testLength:14, testStart: 96, testEnd: 109},
        {title: "Page 4 - Partie 2/2", number: 12, testLength:13, testStart: 110, testEnd: 122},
    ],
};