@baseUrl = http://localhost:3000

### Route GET /test
GET {{baseUrl}}/test

### Pour obtenir les données du jeu
GET {{baseUrl}}/chess/game/data

### Pour reset le board
GET {{baseUrl}}/chess/board/reset

### Test censé être faux pour effectuer un move
POST {{baseUrl}}/chess/move/verif
Content-Type: application/json

{
    "order": "2",
    "piece_id": "p1w",
    "originCase": "a2",
    "destinationCase": "a5",
    "killingMove": false,
    "killCase": null
}